let data = [
  {
    id: 1,
    folded: 'Y',
    gender: 'M',
    brandName: 'HERE&NOW',
    description: 'Men Regular Fit Casual Shirt',
    finalPrice: '824',
    strickPrice: '1499',
    discount: 45,
    productSize: '38, 40, 42, 44, 46',
    link: '/images/M1.jpg',
    isFeatured: true,
  },
  {
    id: 2,
    folded: 'Y',
    gender: 'M',
    brandName: 'Dennis Lingo',
    description: 'Men Slim Fit Casual T-Shirt',
    finalPrice: '554',
    strickPrice: '1849',
    discount: 70,
    productSize: '38, 40, 42, 44, 46',
    link: '/images/M2.jpg',
    isFeatured: true,
  },
  {
    id: 3,
    folded: 'Y',
    gender: 'M',
    brandName: 'HIGHLANDER',
    description: 'Men Slim Fit Shirt',
    finalPrice: '519',
    strickPrice: '1299',
    discount: 60,
    productSize: '39, 40, 42, 44',
    link: '/images/M3.jpg',
    isFeatured: false,
  },
  {
    id: 4,
    folded: 'N',
    gender: 'M',
    brandName: 'Roadster',
    description: 'Regular Fit Check Casual Shirt',
    finalPrice: '879',
    strickPrice: '1599',
    discount: 45,
    productSize: '38, 40, 42, 44',
    link: '/images/M4.jpg',
    isFeatured: false,
  },
  {
    id: 5,
    folded: 'Y',
    gender: 'M',
    brandName: 'Allen Solly',
    description: 'Slim Fit Casual Shirt',
    finalPrice: '1749',
    strickPrice: '2149',
    discount: 19,
    productSize: '38, 40, 42',
    link: '/images/M5.jpg',
    isFeatured: false,
  },
  {
    id: 6,
    folded: 'Y',
    gender: 'M',
    brandName: 'HERE&NOW',
    description: 'Regular Faded Casual Shirt',
    finalPrice: '1044',
    strickPrice: '1899',
    discount: 45,
    productSize: '38, 40, 42, 44, 46',
    link: '/images/M6.jpg',
    isFeatured: false,
  },
  {
    id: 7,
    folded: 'Y',
    gender: 'M',
    brandName: 'Nautica',
    description: 'Classic Fit Casual Shirt',
    finalPrice: '1259',
    strickPrice: '2799',
    discount: 55,
    productSize: '39, 40, 42, 44, 46',
    link: '/images/M7.jpg',
    isFeatured: false,
  },
  {
    id: 8,
    folded: 'N',
    gender: 'M',
    brandName: 'HIGHLANDER',
    description: 'Men Slim Fit Casual Shirt',
    finalPrice: '419',
    strickPrice: '1049',
    discount: 60,
    productSize: '39, 40, 42, 44',
    link: '/images/M8.jpg',
    isFeatured: false,
  },
  {
    id: 9,
    folded: 'N',
    gender: 'M',
    brandName: 'Campus Sutra',
    description: 'Men Standard Fit Casual T-Shirt',
    finalPrice: '599',
    strickPrice: '1499',
    discount: 60,
    productSize: '38, 40, 42, 44',
    link: '/images/M9.jpg',
    isFeatured: true,
  },
  {
    id: 10,
    folded: 'N',
    gender: 'M',
    brandName: 'HERE&NOW',
    description: 'Men Regular Fit Casual Shirt',
    finalPrice: '899',
    strickPrice: '1499',
    discount: 40,
    productSize: '38, 40, 42, 44, 46',
    link: '/images/M10.jpg',
    isFeatured: true,
  },
  {
    id: 11,
    folded: 'Y',
    gender: 'M',
    brandName: 'Dennis Lingo',
    description: 'Men Slim Fit Casual Shirt',
    finalPrice: '554',
    strickPrice: '1849',
    discount: 70,
    productSize: '38, 40, 42, 44, 46',
    link: '/images/M11.jpg',
    isFeatured: true,
  },
  {
    id: 12,
    folded: 'Y',
    gender: 'M',
    brandName: 'GANT',
    description: 'Regular Fit Casual Shirt',
    finalPrice: '2999',
    strickPrice: '5999',
    discount: 50,
    productSize: '38, 40, 42, 44, 46',
    link: '/images/M12.jpg',
    isFeatured: false,
  },
  {
    id: 13,
    folded: 'N',
    gender: 'M',
    brandName: 'HIGHLANDER',
    description: 'Men Slim Fit Casual Shirt',
    finalPrice: '439',
    strickPrice: '1099',
    discount: 60,
    productSize: '39, 40, 42, 44',
    link: '/images/M13.jpg',
    isFeatured: false,
  },
  {
    id: 14,
    folded: 'N',
    gender: 'M',
    brandName: 'RAMRAJ COTTON',
    description: 'Regular Fit Casual Shirt',
    finalPrice: '1749',
    strickPrice: '2199',
    discount: 26,
    productSize: '38, 40, 42, 44',
    link: '/images/M14.jpg',
    isFeatured: false,
  },
  {
    id: 15,
    folded: 'Y',
    gender: 'M',
    brandName: 'HERE&NOW',
    description: 'Men Slim Fit Casual Shirt',
    finalPrice: '1139',
    strickPrice: '1899',
    discount: 40,
    productSize: '38, 40, 42, 44, 46',
    link: '/images/M15.jpg',
    isFeatured: false,
  },
  {
    id: 16,
    folded: 'Y',
    gender: 'M',
    brandName: 'Roadster',
    description: 'Regular Fit Casual Shirt',
    finalPrice: '439',
    strickPrice: '799',
    discount: 45,
    productSize: '38, 40, 42, 44',
    link: '/images/M16.jpg',
    isFeatured: false,
  },
  {
    id: 17,
    folded: 'Y',
    gender: 'M',
    brandName: 'Allen Solly',
    description: 'Slim Fit Casual Shirt',
    finalPrice: '1899',
    strickPrice: '2399',
    discount: 18,
    productSize: '39, 40, 42',
    link: '/images/M17.jpg',
    isFeatured: false,
  },
  {
    id: 18,
    folded: 'Y',
    gender: 'M',
    brandName: 'HIGHLANDER',
    description: 'Men Slim Fit Casual Shirt',
    finalPrice: '439',
    strickPrice: '1099',
    discount: 60,
    productSize: '39, 40, 42, 44',
    link: '/images/M18.jpg',
    isFeatured: true,
  },
  {
    id: 19,
    folded: 'Y',
    gender: 'F',
    brandName: 'Roadster',
    description: 'Women Slim Fit Casual Shirt',
    finalPrice: '779',
    strickPrice: '1299',
    discount: 40,
    productSize: 'S, M, L, XL',
    link: '/images/F1.jpg',
    isFeatured: true,
  },
  {
    id: 20,
    folded: '',
    gender: 'F',
    brandName: 'People',
    description: 'Regular Fit Casual Shirt',
    finalPrice: '1400',
    strickPrice: '2219',
    discount: 39,
    productSize: 'XS, S, M, L, XL, XXL',
    link: '/images/F2.jpg',
    isFeatured: false,
  },
  {
    id: 21,
    folded: 'N',
    gender: 'F',
    brandName: 'Imfashini',
    description: 'Casual Shirt with Mask',
    finalPrice: '499',
    strickPrice: '1785',
    discount: 72,
    productSize: 'XS, S, M, L, XL',
    link: '/images/F3.jpg',
    isFeatured: false,
  },
  {
    id: 22,
    folded: 'N',
    gender: 'F',
    brandName: 'Kook N Keech',
    description: 'Regular Printed Casual Shirt',
    finalPrice: '539',
    strickPrice: '1199',
    discount: 55,
    productSize: 'XS, S, M, L, XL',
    link: '/images/F4.jpg',
    isFeatured: false,
  },
  {
    id: 23,
    folded: 'N',
    gender: 'F',
    brandName: 'Kook N Keech Disney',
    description: 'Women Regular Fit Casual Shirt',
    finalPrice: '719',
    strickPrice: '1799',
    discount: 60,
    productSize: 'XS, S, M, L, XL',
    link: '/images/F5.jpg',
    isFeatured: true,
  },
  {
    id: 24,
    folded: 'N',
    gender: 'F',
    brandName: 'Roadster',
    description: 'Polka Dots Print Casual Shirt',
    finalPrice: '699',
    strickPrice: '999',
    discount: 30,
    productSize: 'XS, S, M, L, XL',
    link: '/images/F6.jpg',
    isFeatured: false,
  },
  {
    id: 25,
    folded: 'Y',
    gender: 'F',
    brandName: 'Berrylush',
    description: 'Women Regular Fit Casual Shirt',
    finalPrice: '683',
    strickPrice: '1798',
    discount: 62,
    productSize: 'S, M, L, XL',
    link: '/images/F7.jpg',
    isFeatured: false,
  },
  {
    id: 26,
    folded: 'N',
    gender: 'F',
    brandName: 'MANGO',
    description: 'Regular Fit Casual Shirt',
    finalPrice: '1049',
    strickPrice: '1498',
    discount: 23,
    productSize: 'XS, S, M, L, XL',
    link: '/images/F8.jpg',
    isFeatured: false,
  },
  {
    id: 27,
    folded: 'Y',
    gender: 'F',
    brandName: 'Roadster',
    description: 'Regular Fit Casual Shirt',
    finalPrice: '909',
    strickPrice: '1299',
    discount: 30,
    productSize: 'S, M, L, XL',
    link: '/images/F9.jpg',
    isFeatured: false,
  },
  {
    id: 28,
    folded: 'N',
    gender: 'F',
    brandName: 'MANGO',
    description: 'Semi-Sheer Longline Shirt',
    finalPrice: '1349',
    strickPrice: '1899',
    discount: 32,
    productSize: 'S, M, L',
    link: '/images/F10.jpg',
    isFeatured: false,
  },
  {
    id: 29,
    folded: 'N',
    gender: 'F',
    brandName: 'KASSUALLY',
    description: 'Women Regular Fit Casual Shirt',
    finalPrice: '584',
    strickPrice: '1425',
    discount: 59,
    productSize: 'XS, S, M, L, XL, XXL',
    link: '/images/F11.jpg',
    isFeatured: false,
  },
  {
    id: 30,
    folded: 'N',
    gender: 'F',
    brandName: 'People',
    description: 'Slim Fit Casual Shirt',
    finalPrice: '789',
    strickPrice: '1199',
    discount: 29,
    productSize: 'XS, S, M, L, XL',
    link: '/images/F12.jpg',
    isFeatured: true,
  },
  {
    id: 31,
    folded: 'N',
    gender: 'F',
    brandName: 'DressBerry',
    description: 'Women Regular Fit Casual Shirt',
    finalPrice: '799',
    strickPrice: '1249',
    discount: 27,
    productSize: 'XS, S, M, L, XL',
    link: '/images/F13.jpg',
    isFeatured: false,
  },
  {
    id: 32,
    folded: 'Y',
    gender: 'F',
    brandName: 'DOROTHY PERKINS',
    description: 'Pocket Detailing Casual Shirt',
    finalPrice: '2371',
    strickPrice: '2790',
    discount: 15,
    productSize: 'M, L, XL, XXL',
    link: '/images/F14.jpg',
    isFeatured: false,
  },
  {
    id: 33,
    folded: 'Y',
    gender: 'F',
    brandName: 'Roadster',
    description: 'Regular Fit Solid Casual Shirt',
    finalPrice: '1199',
    strickPrice: '1799',
    discount: 31,
    productSize: 'S, M, L, XL',
    link: '/images/F15.jpg',
    isFeatured: true,
  },
  {
    id: 34,
    folded: 'N',
    gender: 'F',
    brandName: 'Roadster',
    description: 'Regular Fit Solid Casual Shirt',
    finalPrice: '999',
    strickPrice: '1699',
    discount: 32,
    productSize: 'S, M, L, XL',
    link: '/images/F16.jpg',
    isFeatured: true,
  },
  {
    id: 35,
    folded: 'N',
    gender: 'F',
    brandName: 'Park Avenue',
    description: 'Women Slim Fit Casual Shirt',
    finalPrice: '559',
    strickPrice: '1599',
    discount: 65,
    productSize: 'XS, S, M, L, XL',
    link: '/images/F17.jpg',
    isFeatured: false,
  },
  {
    id: 36,
    folded: 'N',
    gender: 'F',
    brandName: 'Annabelle by Pantaloons',
    description: 'Women Regular Fit Formal Shirt',
    finalPrice: '719',
    strickPrice: '899',
    discount: 20,
    productSize: 'XS, S, M, L, XL, XXL',
    link: '/images/F18.jpg',
    isFeatured: false,
  },
  {
    id: 37,
    folded: 'N',
    gender: 'F',
    brandName: 'Tokyo Talkies',
    description: 'Regular Fit Casual Shirt',
    finalPrice: '459',
    strickPrice: '1149',
    discount: 60,
    productSize: 'S, M, L, XL',
    link: '/images/F19.jpg',
    isFeatured: true,
  },
];
export function getallCloths() {
  return data;
}
export function getMaleCloths() {
  return data.filter((event) => event.gender === 'M');
}

export function getFemaleCloths() {
  return data.filter((event) => event.gender === 'F');
}
export function getFoldedSleevesCloths() {
  return data.filter((event) => event.folded === 'Y');
}
export function filteredBySize() {
  return data.filter((event) => event.productSize);
}
export function getBrands() {
  return data.filter((event) => event.brandName);
}
export function getFeaturedProducts() {
  return data.filter((event) => event.isFeatured);
}
