import { title } from "process";

export const shopTabLinks = [
  {
    title: "By Products",
    link: [
      { title: "view all", url: "/" },
      { title: " T - Shirts", url: "/" },
      { title: "Oversized T-Shirts", url: "/" },
      { title: "Drop Cut T-Shirts", url: "/" },
      { title: "Hoodies", url: "/" },
      { title: "Sweatshirts", url: "/" },
      { title: "Jackets", url: "/" },
      { title: "Fullsleeve T-Shirts", url: "/" },
      { title: "Basics", url: "/" },
      { title: "Kids T-Shirts", url: "/" },
      { title: "Sleeveless T-Shirts & Tank Tops", url: "/" },
    ],
  },
  {
    title: "Accessories",
    link: [
      { title: "View All", url: "/" },
      { title: "Stickers", url: "/" },
      { title: "Mobile Covers", url: "/" },
      { title: "Mugs", url: "/" },
      { title: "Caps", url: "/" },
      { title: "Posters", url: "/" },
      { title: "Face Masks", url: "/" },
      { title: "Fridge Magnets", url: "/" },
      { title: "Coasters", url: "/" },
      { title: "Badges", url: "/" },
      { title: "Spiral Notebooks", url: "/" },
      { title: "Pins", url: "/" },
      { title: "Socks", url: "/" },
      { title: "Mouse Pads", url: "/" },
      { title: "Laptop Skins", url: "/" },
      { title: "Key Chains", url: "/" },
      { title: "Tote Bags", url: "/" },
    ],
  },
  {
    title: "By Popular Themes",
    link: [
      { title: " All Products", url: "/" },
      { title: "Superheroes", url: "/" },
      { title: "Anime", url: "/" },
      { title: "Cartoons", url: "/" },
      { title: "Comics", url: "/" },
      { title: "Glow In The Dark", url: "/" },
      { title: "Horror", url: "/" },
      { title: "Film", url: "/" },
      { title: "TV", url: "/" },
      { title: "Slogan", url: "/" },
      { title: "Funny", url: "/" },
      { title: "Music", url: "/" },
      { title: "Cute", url: "/" },
      { title: "Geek", url: "/" },
      { title: "Animals", url: "/" },
      { title: "Funky", url: "/" },
      { title: "Foodie", url: "/" },
      { title: "Stoner & Alcohol", url: "/" },
      { title: "Pattern T-Shirts", url: "/" },
      { title: "Camouflage", url: "/" },
      { title: "Gym", url: "/" },
      { title: "Rick And Morty", url: "/" },
      { title: "Avengers T-Shirts", url: "/" },
      { title: "Marvel T-Shirts", url: "/" },
      { title: "Iron Man T-Shirts", url: "/" },
      { title: "Gaming", url: "/" },
      { title: "GIFT VOUCHERS", url: "/" },
      { title: "OFFICIAL MERCHANDISE", url: "/" },
      { title: "UGLY CHRISTMAS SWEATERS", url: "/" },
      { title: "CLEARANCE SALE", url: "/" },
      { title: "MINIONS", url: "/" },
      { title: "PRE-ORDERS", url: "/" },
      { title: "ARCHIVE", url: "/" },
      { title: "BULK & CUSTOM ORDERS", url: "/" },
    ],
  },
];
export const menTabLinks = [
  {
    title: "Men Apparel",
    link: [
      { title: " View All", url: "/" },
      { title: "Mens Hoodies", url: "/" },
      { title: "Mens Sweatshirts", url: "/" },
      { title: "Mens Jackets", url: "/" },
      { title: "Mens T-Shirts", url: "/" },
      { title: "Mens Oversized T-Shirts", url: "/" },
      { title: "Mens Drop Cut T-Shirts", url: "/" },
      { title: "Mens Fullsleeve T-Shirts", url: "/" },
      { title: "Mens Basics", url: "/" },
      { title: "Mens Sleeveless T-Shirts & Tank Tops", url: "/" },
    ],
  },
];
export const womenTabLinks = [
  {
    title: "Women Apparel",
    link: [
      { title: "View All", url: "/" },
      { title: "Womens T-Shirts", url: "/" },
      { title: "Womens Full Sleeve T-Shirts", url: "/" },
      { title: "Womens Oversized T-Shirts", url: "/" },
      { title: "Womens Printed T-Shirts", url: "/" },
      { title: "Womens Hoodies", url: "/" },
      { title: "Womens Basics", url: "/" },
      { title: "Boyfriend T-Shirts", url: "/" },
    ],
  },
];
export const accessoriesTabLinks = [
  {
    title: "Accessories",
    link: [
      { title: "View All", url: "/" },
      { title: "Stickers", url: "/" },
      { title: "Mobile Covers", url: "/" },
      { title: "Mugs", url: "/" },
      { title: "Caps", url: "/" },
      { title: "Posters", url: "/" },
      { title: "Face Masks", url: "/" },
      { title: "Fridge Magnets", url: "/" },
      { title: "Coasters", url: "/" },
      { title: "Badges", url: "/" },
      { title: "Spiral Notebooks", url: "/" },
      { title: "Pins", url: "/" },
      { title: "Socks", url: "/" },
      { title: "Mouse Pads", url: "/" },
      { title: "Laptop Skins", url: "/" },
      { title: "Key Chains", url: "/" },
      { title: "Tote Bags", url: "/" },
    ],
  },
];

export const characterTabLinks = [
  {
    title: "MARVEL",
    link: [
      { title: " Marvel Merchandise", url: "/" },
      { title: "Avengers", url: "/" },
      { title: "Spider-Man", url: "/" },
      { title: "Iron Man", url: "/" },
      { title: "Captain America", url: "/" },
      { title: "Thor", url: "/" },
      { title: "Loki", url: "/" },
      { title: "Doctor Strange", url: "/" },
      { title: "Deadpool", url: "/" },
      { title: "Black Panther", url: "/" },
      { title: "Guardians Of The Galaxy", url: "/" },
      { title: "Across The Spider-Verse", url: "/" },
      { title: "The Hulk", url: "/" },
      { title: "The Punisher", url: "/" },
      { title: "Black Widow", url: "/" },
      { title: "Venom", url: "/" },
      { title: "WandaVision", url: "/" },
      { title: "Ant-Man", url: "/" },
      { title: "X-Men", url: "/" },
      { title: "The Falcon And The Winter Soldier", url: "/" },
      { title: "What If...?", url: "/" },
      { title: "Captain Marvel", url: "/" },
      { title: "Wolverine", url: "/" },
      { title: "Ms Marvel", url: "/" },
      { title: "Moon Knight", url: "/" },
      { title: "She-Hulk", url: "/" },
      { title: "Daredevil", url: "/" },
      { title: "Hawkeye", url: "/" },
      { title: "Ghost Rider", url: "/" },
      { title: "Shang Chi", url: "/" },
      { title: "Eternals", url: "/" },
      { title: "Werewolf By Night", url: "/" },
      { title: "Carnage", url: "/" },
      { title: "Thanos", url: "/" },
    ],
  },
  {
    title: "DC COMICS",
    link: [
      { title: "DC Comics Merchandise", url: "/" },
      { title: "Blue Beetle", url: "/" },
      { title: "Justice League", url: "/" },
      { title: "Batman", url: "/" },
      { title: "The Flash", url: "/" },
      { title: "Superman", url: "/" },
      { title: "Wonder Woman", url: "/" },
      { title: "Shazam", url: "/" },
      { title: "Joker", url: "/" },
      { title: "Aquaman", url: "/" },
      { title: "Green Lantern", url: "/" },
      { title: "Harley Quinn", url: "/" },
      { title: "Black Adam", url: "/" },
      { title: "Suicide Squad", url: "/" },
    ],
  },
  {
    title: "Anime",
    link: [{ title: "Naruto", url: "/" }],
  },
  {
    title: "MOVIES AND TV",
    link: [
      { title: "Harry Potter", url: "/" },
      { title: "Friends", url: "/" },
      { title: "Star Wars", url: "/" },
      { title: "The Mandalorian", url: "/" },
      { title: "House Of The Dragon", url: "/" },
      { title: "Game Of Thrones", url: "/" },
      { title: "The Matrix", url: "/" },
      { title: "Boba Fett", url: "/" },
      { title: "Fantastic Beasts", url: "/" },
      { title: "The Big Bang Theory", url: "/" },
      { title: "The Lion King", url: "/" },
    ],
  },
  {
    title: "CARTOONS / ANIMATION",
    link: [
      { title: "Garfield", url: "/" },
      { title: "Snoopy", url: "/" },
      { title: "Rick & Morty", url: "/" },
      { title: "Looney Tunes", url: "/" },
      { title: "Bugs Bunny", url: "/" },
      { title: "Daffy Duck", url: "/" },
      { title: "Tweety", url: "/" },
      { title: "Space Jam", url: "/" },
      { title: "Tom And Jerry", url: "/" },
      { title: "Scooby Doo", url: "/" },
      { title: "Disney", url: "/" },
      { title: "Mickey Mouse", url: "/" },
      { title: "Donald Duck", url: "/" },
      { title: "Cartoon Network", url: "/" },
      { title: "Ed, Edd And Eddy", url: "/" },
      { title: "Samurai Jack", url: "/" },
      { title: "Mojo Jojo", url: "/" },
      { title: "The Powerpuff Girls", url: "/" },
      { title: "Johnny Bravo", url: "/" },
      { title: "Courage The Cowardly Dog", url: "/" },
      { title: "Dexter's Laboratory", url: "/" },
      { title: "Ben 10", url: "/" },
      { title: "Adventure Time", url: "/" },
      { title: "Spongebob Squarepants", url: "/" },
      { title: "South Park", url: "/" },
      { title: "TMNT", url: "/" },
      { title: "Fido Dido", url: "/" },
    ],
  },
  {
    title: "COLLABORATIONS",
    link: [
      { title: "ISRO", url: "/" },
      { title: "NASA", url: "/" },
    ],
  },
];
export const artistMerchandiseTabLinks = [
  {
    title: "COMEDY",
    link: [
      { title: "Trevor Noah", url: "/" },
      { title: "Samay Raina", url: "/" },
      { title: "Aakash Mehta", url: "/" },
      { title: "Akshar Pathak", url: "/" },
      { title: "Bollywood Gandu", url: "/" },
      { title: "CallMeShazzam", url: "/" },
    ],
  },
  {
    title: "MUSIC",
    link: [
      { title: "Goo Goo Dolls", url: "/" },
      { title: "Lollapalooza", url: "/" },
      { title: "Westlife", url: "/" },
      { title: "KING", url: "/" },
      { title: "Ziro", url: "/" },
      { title: "Prateek Kuhad", url: "/" },
      { title: "Parikrama", url: "/" },
      { title: "Sabotage", url: "/" },
      { title: "Fallen Letters", url: "/" },
      { title: "The Down Troddence", url: "/" },
      { title: "Control ALT Delete", url: "/" },
      { title: "Nucleya", url: "/" },
      { title: "Aabha Hanjura", url: "/" },
      { title: "Primitiv", url: "/" },
      { title: "Skyharbor", url: "/" },
      { title: "Blackstratblues", url: "/" },
      { title: "Pangea", url: "/" },
      { title: "Goddess Gagged", url: "/" },
      { title: "Sanam", url: "/" },
      { title: "Wolves", url: "/" },
      { title: "Scribe", url: "/" },
      { title: "Pentagram", url: "/" },
      { title: "Punk On Toast", url: "/" },
      { title: "Demonstealer", url: "/" },
      { title: "Demonic Resurrection", url: "/" },
      { title: "Su Real", url: "/" },
      { title: "Bombay Bassment", url: "/" },
      { title: "R.A.I.D", url: "/" },
      { title: "Undying Inc.", url: "/" },
      { title: "Killchain", url: "/" },
      { title: "Antariksh", url: "/" },
      { title: "Vinay Kaushal", url: "/" },
      { title: "Deathknell", url: "/" },
      { title: "Project Mishram", url: "/" },
      { title: "Pinecone Records", url: "/" },
    ],
  },
  {
    title: "WEBSERIES",
    link: [
      { title: "Shit Indians Say & The Sarcastic Indian", url: "/" },
      { title: "Bacon Tadka", url: "/" },
      { title: "Headbanger's Kitchen", url: "/" },
      { title: "The Big Forkers", url: "/" },
    ],
  },
  {
    title: "MOVIES",
    link: [{ title: "Bhediya", url: "/" }],
  },
  {
    title: "OTHER",
    link: [
      { title: "Parle-G", url: "/" },
      { title: "WazirX", url: "/" },
      { title: "ABP Network", url: "/" },
      { title: "Nomads Of India", url: "/" },
      { title: "Bingo! Achha Aaloo", url: "/" },
      { title: "Doodleodrama", url: "/" },
      { title: "Chess.Com", url: "/" },
      { title: "Vitamin Stree", url: "/" },
      { title: "Moonshine", url: "/" },
      { title: "SensibleTshirts", url: "/" },
    ],
  },
  {
    title: "VIEW ALL",
    link: [],
  },
];
export const footerLinks = [
  {
    title: "Information",
    link: [
      { title: " About Us", url: "/about" },
      { title: "Delivery Information", url: "/" },
      { title: "Return Policy", url: "/" },
      { title: "Frequently Asked Questions", url: "/" },
      { title: "Terms & Conditions", url: "/" },
      { title: "Privacy Policy", url: "/" },
      { title: "Bulk & Custom Orders", url: "/" },
      { title: "Preorder Campaigns", url: "/" },
      { title: "Campus Ambassador Program", url: "/" },
    ],
  },
  {
    title: "Extras",
    link: [
      { title: "Gift Vouchers", url: "/" },
      { title: "Affiliates", url: "/" },
      { title: "Fan wall", url: "/" },
      { title: "Site Map", url: "/" },
    ],
  },
  {
    title: "Customer Service",
    link: [
      { title: "Contact US", url: "/contact-us" },
      { title: "Request A return" },
    ],
  },
  {
    title: "My Account",
    link: [
      { title: "My Account", url: "/my-account" },
      { title: "Order History", url: "/order-history" },
      { title: "newsletter", url: "/newsletter" },
    ],
  },
  {
    title: "Social Media",
    link: [
      { title: "Facebook", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Pintrest", url: "/" },
    ],
  },
];
